environment:
  PROJECT_NAME: bridges
  matrix:
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build_script:
  # Generate artifacts for release
  - cargo build --release
  - mkdir deploy
  - copy target\release\%PROJECT_NAME%.exe deploy
  - cd deploy
    # release zipfile will look like 'rust-everywhere-v1.2.3-x86_64-pc-windows-msvc'
  - 7z a ../%PROJECT_NAME%-%TARGET%.zip *
  - cd ..
  - ls

artifacts:
  - path: '%PROJECT_NAME%-%TARGET%.zip'
    name: '%PROJECT_NAME%-%TARGET%'

deploy:
  description: 'Windows release'
  # All the zipped artifacts will be deployed
  artifact: /.*\.zip/
  auth_token:
    secure: F1UkKeXIf6IItNy1am/vJeA1Qls783JStLkeYgF03TUknD3E+n5JHRBptKqtycrS
  provider: GitHub
  on:
    appveyor_repo_tag: true
