[package]
name = "bridges"
version = "0.3.0"
description = "A simple UDP-Serial interface."
readme = "README.md"
license = "MIT"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
homepage = "https://github.com/patrickelectric/bridges"
repository = "https://github.com/patrickelectric/bridges"
keywords = ["cli", "serial", "udp"]
categories = ["command-line-utilities"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
path = "src/main.rs"
name = "bridges"

[dependencies]
clap = "2.31.2"
libc = "0.2.62"
mio = "0.6"
mio-serial = "3.2.0"
serialport = "3.2.0"
